# Generated by Django 3.2.7 on 2021-09-22 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('Doctor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Appointment_Date', models.DateField(default=datetime.datetime(2021, 9, 22, 16, 34, 14, 271241))),
                ('Phone', models.IntegerField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.doctors')),
            ],
        ),
    ]
